on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    name: init
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        id: init
        with:
          args: init --output CHANGELOG.md --compare-url https://example.com/abcdef...HEAD
